---
# roles/gitea/defaults/main.yml

## Deployment Management

gitea_net_port_http: "8081"
gitea_net_port_ssh: "2222"
gitea_net_name: "gitea"

## Database Management

gitea_db_image_name: "docker.io/library/mariadb"
gitea_db_image_tag: "10"
gitea_db_image_auto_update: true

gitea_db_name: "gitea"
gitea_db_user: "gitea"
gitea_db_pass: "{{ database_pass | mandatory }}"

## App Management

gitea_app_image_name: "docker.io/gitea/gitea"
gitea_app_image_tag: "1"
gitea_app_image_auto_update: true

gitea_admin_user: "gitea-admin"
gitea_admin_pass: "{{ admin_pass | mandatory }}"
...
