---
# roles/mariadb/tasks/main.yml

## Prerequisites

- name: "Manage podman Socket"
  ansible.builtin.service:
    name: "podman.socket"
    state: "started"
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "service"

- name: "Manage podman-auto-update Timer"
  ansible.builtin.service:
    name: "podman-auto-update.timer"
    enabled: true
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "service"

## Network

- name: "Create mariadb Podman Network"
  containers.podman.podman_network:
    name: "{{ mariadb_net_name }}"
    state: "present"
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "network"

## dblication

- name: "Pull mariadb-db Image"
  containers.podman.podman_image:
    name: "{{ mariadb_db_image_name }}"
    tag: "{{ mariadb_db_image_tag }}"
    state: "present"
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "image"

- name: "Create mariadb-db Service File"
  ansible.builtin.template:
    src: "container-mariadb-db.service.j2"
    dest: "/etc/systemd/system/container-mariadb-db.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "service"

- name: "Start & Enable mariadb-db Service"
  ansible.builtin.systemd:
    name: "container-mariadb-db.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - "mariadb"
    - "podman"
    - "service"
...
