---
# roles/homer/tasks/main.yml

## Prerequisites

- name: "Manage podman Socket"
  ansible.builtin.service:
    name: "podman.socket"
    state: "started"
  become: true
  tags:
    - "homer"
    - "podman"
    - "service"

- name: "Manage podman-auto-update Timer"
  ansible.builtin.service:
    name: "podman-auto-update.timer"
    enabled: true
  become: true
  tags:
    - "homer"
    - "podman"
    - "service"

## Network

- name: "Create homer Podman Network"
  containers.podman.podman_network:
    name: "{{ homer_net_name }}"
    state: "present"
  become: true
  tags:
    - "homer"
    - "podman"
    - "network"

## Application

- name: "Pull homer-app Image"
  containers.podman.podman_image:
    name: "{{ homer_app_image_name }}"
    tag: "{{ homer_app_image_tag }}"
    state: "present"
  become: true
  tags:
    - "homer"
    - "podman"
    - "image"

- name: "Create homer-app Volume"
  containers.podman.podman_volume:
    name: "{{ homer_app_volume }}"
    state: "present"
  register: "r_volume"
  become: true
  tags:
    - "homer"
    - "podman"
    - "volume"

- name: "Manage homer-app Configuration"
  ansible.builtin.template:
    src: "{{ homer_config_src }}"
    dest: "{{ r_volume.volume.Mountpoint }}/config.yml"
  become: true
  tags:
    - "homer"
    - "podman"
    - "service"

- name: "Create homer-app Service File"
  ansible.builtin.template:
    src: "container-homer-app.service.j2"
    dest: "/etc/systemd/system/container-homer-app.service"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  tags:
    - "homer"
    - "podman"
    - "service"

- name: "Start & Enable homer-app Service"
  ansible.builtin.systemd:
    name: "container-homer-app.service"
    state: "started"
    enabled: true
    daemon_reload: true
  become: true
  tags:
    - "homer"
    - "podman"
    - "service"
...
